# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["jchampion@fastly.com"]
description = ""
language = "javascript"
manifest_version = 2
name = "local-config"
service_id = ""

[scripts]
  build = "npm run build"

[local_server]
  [local_server.config_stores]
    [local_server.config_stores.testconfig]
      format = "json"
      file = "./example.json"
